In [37]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='0nKO2JbMw8Kr0-qVU5NL823ypweLKZgHAGeeXHScI8ZZ',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'predictingperformanceofcarusingma-donotdelete-pr-uevfr2e7e3of1k'
object_key = 'car performance dataset.CSV'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

datas= pd.read_csv(body)
datas.head()


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [38]:
type(datas)

pandas.core.frame.DataFrame

In [39]:
datas.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [40]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
datas["car name"] = l.fit_transform(datas["car name"])
datas["horsepower"] = l.fit_transform(datas["horsepower"])
datas.head(10)


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0          15    3504          12.0   
1  15.0          8         350.0          33    3693          11.5   
2  18.0          8         318.0          27    3436          11.0   
3  16.0          8         304.0          27    3433          12.0   
4  17.0          8         302.0          22    3449          10.5   
5  15.0          8         429.0          40    4341          10.0   
6  14.0          8         454.0          45    4354           9.0   
7  14.0          8         440.0          44    4312           8.5   
8  14.0          8         455.0          46    4425          10.0   
9  15.0          8         390.0          38    3850           8.5   

   model year  origin  car name  
0          70       1        49  
1          70       1        36  
2          70       1       230  
3          70       1        14  
4          70       1       160  
5          70       1       140  
6          70       1        54  
7          70       1       222  
8          70       1       240  
9          70       1         1

In [41]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    int64  
dtypes: float64(3), int64(6)
memory usage: 28.1 KB


In [42]:
datas['car name'].unique()

array([ 49,  36, 230,  14, 160, 140,  54, 222, 240,   1, 100, 214,  16,
       257,  22,   7, 132,  67, 111, 162,  94,  64, 270, 155, 231, 161,
        10, 241, 115, 128, 249,   9,  63, 242, 150, 186, 207, 209, 122,
       266,  75, 283, 217, 271, 104, 290,  62, 157,   2, 191,  31, 202,
        74, 182,  11,  48, 142, 232, 292, 280, 211, 252, 156,  84, 277,
       103, 267,  25,  55, 141, 108, 192,  44, 147, 221,  73,  29,   0,
       234,  61,   8, 149, 219, 289, 127, 218, 206, 262,  86, 173, 187,
       120,  58, 243, 123, 208,  17, 291, 112, 259, 274, 203,  60,  91,
        50, 233,  27, 109,  21, 281,  87, 102, 121, 166, 260, 126, 235,
       193,  42, 223,  24,  41, 220,  34,  59, 153, 265, 239, 284,  12,
       210, 293, 170, 124,  40, 253, 107,  51,  65, 299,  99, 144, 251,
        13,  90, 294, 238, 185,  39,  66, 131, 110, 164,  32, 255, 215,
        93, 201, 116, 188,  53,  35, 237, 143, 244,  57,  69, 159, 285,
       250, 268, 154, 106, 261,  88,  23, 180, 286, 138, 179,  9

In [43]:
x = datas.iloc[:,1:8].values
x

array([[  8. , 307. ,  15. , ...,  12. ,  70. ,   1. ],
       [  8. , 350. ,  33. , ...,  11.5,  70. ,   1. ],
       [  8. , 318. ,  27. , ...,  11. ,  70. ,   1. ],
       ...,
       [  4. , 135. ,  78. , ...,  11.6,  82. ,   1. ],
       [  4. , 120. ,  73. , ...,  18.6,  82. ,   1. ],
       [  4. , 119. ,  76. , ...,  19.4,  82. ,   1. ]])

In [44]:
y = datas.iloc[:,0:1]

In [45]:
y

mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [47]:
x.shape

(398, 7)

In [48]:
x_train

array([[  8. , 318. ,  27. , ...,  13.5,  72. ,   1. ],
       [  4. ,  97. ,  55. , ...,  19. ,  71. ,   2. ],
       [  4. ,  97. ,  72. , ...,  15.8,  80. ,   2. ],
       ...,
       [  4. ,  68. ,  50. , ...,  19.5,  73. ,   2. ],
       [  6. , 250. ,   0. , ...,  15. ,  71. ,   1. ],
       [  4. ,  90. ,  66. , ...,  16.5,  75. ,   2. ]])

In [49]:
from sklearn.preprocessing import StandardScaler 
sd = StandardScaler()
x_train = sd.fit_transform(x_train)
x_test = sd.fit_transform(x_test)


In [50]:
x_train

array([[ 1.45688373,  1.17792929, -0.78901285, ..., -0.74595501,
        -1.13752513, -0.72391106],
       [-0.86536703, -0.93362716,  0.15589238, ...,  1.2459157 ,
        -1.41177304,  0.52043336],
       [-0.86536703, -0.93362716,  0.72958484, ...,  0.0870091 ,
         1.05645814,  0.52043336],
       ...,
       [-0.86536703, -1.21070922, -0.01284069, ...,  1.42699485,
        -0.86327722,  0.52043336],
       [ 0.29575835,  0.52821961, -1.70017146, ..., -0.20271754,
        -1.41177304, -0.72391106],
       [-0.86536703, -1.00050903,  0.52710515, ...,  0.34051992,
        -0.31478141,  0.52043336]])

In [51]:
y_train

mpg
64   15.0
55   27.0
317  34.3
102  26.0
358  31.6
..    ...
323  27.9
192  22.0
117  29.0
47   19.0
172  25.0

[318 rows x 1 columns]

In [52]:
from sklearn.ensemble import RandomForestRegressor
d = RandomForestRegressor (n_estimators=30,random_state = 0)
d.fit(x_train,y_train)


/tmp/wsuser/ipykernel_166/3243555072.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  d.fit(x_train,y_train)


RandomForestRegressor(n_estimators=30, random_state=0)

In [53]:
r = d.predict(x_test)
r

array([13.7       , 24.39666667, 14.55      , 21.22333333, 18.28      ,
       30.6       , 34.17333333, 21.81666667, 17.09      , 25.88666667,
       35.48333333, 36.47666667, 19.48      , 24.27      , 16.65666667,
       33.92333333, 28.26      , 26.27666667, 18.04333333, 36.16666667,
       16.63333333, 22.86      , 24.32      , 20.56666667, 33.39      ,
       27.08666667, 33.48      , 32.05333333, 31.77666667, 16.69666667,
       20.32666667, 32.65333333, 20.55333333, 33.15333333, 22.65      ,
       24.80333333, 19.38333333, 17.30666667, 34.60666667, 13.03333333,
       15.3       , 15.56666667, 28.89666667, 36.85      , 29.33333333,
       22.33333333, 20.38333333, 16.42      , 22.66333333, 30.46666667,
       33.59333333, 28.44666667, 17.26666667, 28.9       , 16.7       ,
       13.63333333, 19.23333333, 26.06333333, 32.28666667, 17.00333333,
       20.03      , 24.65333333, 19.92666667, 16.53333333, 13.73333333,
       14.71666667, 14.5       , 19.31666667, 24.39333333, 14.76

In [54]:
import pickle
pickle.dump(d,open('regression.pkl','wb'))

In [55]:
import seaborn as sns
sns.pairplot(data=datas)


In [56]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,r)
accuracy

0.8784089763810866

In [57]:
import numpy as np

In [58]:
r =d.predict(np.array([[8,307,130,3504,12,70,1]]))
r

array([19.74])

In [59]:
from sklearn.svm import SVR
svm = SVR(kernel = 'linear')
svm.fit(x_train,y_train)

/opt/conda/envs/Python-3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [60]:
y_pre = svm.predict(x_test)

In [61]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pre)

In [62]:
accuracy

0.8293190579714911

In [63]:
import pickle
pickle.dump(d,open('regression.pkl','wb'))

In [64]:
y_pred=d.predict(x_test)
y_pred

array([13.7       , 24.39666667, 14.55      , 21.22333333, 18.28      ,
       30.6       , 34.17333333, 21.81666667, 17.09      , 25.88666667,
       35.48333333, 36.47666667, 19.48      , 24.27      , 16.65666667,
       33.92333333, 28.26      , 26.27666667, 18.04333333, 36.16666667,
       16.63333333, 22.86      , 24.32      , 20.56666667, 33.39      ,
       27.08666667, 33.48      , 32.05333333, 31.77666667, 16.69666667,
       20.32666667, 32.65333333, 20.55333333, 33.15333333, 22.65      ,
       24.80333333, 19.38333333, 17.30666667, 34.60666667, 13.03333333,
       15.3       , 15.56666667, 28.89666667, 36.85      , 29.33333333,
       22.33333333, 20.38333333, 16.42      , 22.66333333, 30.46666667,
       33.59333333, 28.44666667, 17.26666667, 28.9       , 16.7       ,
       13.63333333, 19.23333333, 26.06333333, 32.28666667, 17.00333333,
       20.03      , 24.65333333, 19.92666667, 16.53333333, 13.73333333,
       14.71666667, 14.5       , 19.31666667, 24.39333333, 14.76

In [65]:
!pip install -U ibm-watson-machine-learning
!tar -zcvf car_performance_model.tgz parkinson.pkl


tar: parkinson.pkl: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors


In [66]:
from ibm_watson_machine_learning import APIClient
wml_credentials={"url":"https://us-south.ml.cloud.ibm.com", 
                 "apikey": "0T81aAhdDix560lMJHNQBh8rihW1OR_0_XDT564hcEGH"
                }
client=APIClient(wml_credentials)


In [67]:
def guide_from_space_name(client,space_name):
    space=client.spaces.get_details()
    return(next(item for item in space['resources']if item['entity']["name"]==space_name)['metadata']['id'])

In [68]:
space_uid=guide_from_space_name(client,'car_performance_deploy')
print("Space UID =" + space_uid)

Space UID =a4f6affd-01ef-42a6-87a3-1817d978c74b


In [69]:
client.set.default_space(space_uid)


'SUCCESS'

In [70]:
client.software_specifications.list()


-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [71]:
software_spec_uid=client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [72]:
model_details=client.repository.store_model(model='car_performance_model.tgz',meta_props={
    client.repository.ModelMetaNames.NAME:"car_model",
    client.repository.ModelMetaNames.TYPE:"scikit-learn_1.0",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid})
model_id=client.repository.get_model_id(model_details)

In [73]:
model_id


'f3f66545-a9a9-41de-90a7-e9ad6abfa93e'

In [75]:
client.repository.download("f3f66545-a9a9-41de-90a7-e9ad6abfa93e","car.tar.gz")


Successfully saved model content to file: 'car.tar.gz'


'/home/wsuser/work/car.tar.gz'